language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
before_install:
- openssl aes-256-cbc -K $encrypted_756bcdda7b95_key -iv $encrypted_756bcdda7b95_iv
  -in id_rsa.enc -out id_rsa -d
- chmod 600 id_rsa
- echo -e "Host 43.93.148.206\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
