language: node_js
node_js:
- '10'
cache:
  directories:
  - node_modules
install:
- npm install
before_script: 
script:
- npm run dev
after_script:
- cd ./dist
- git init
- git config user.name "${U_NAME}"
- git config user.email "${U_EMAIL}"
- git add .
- git commit -m "Update tools"
- git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:${P_BRANCH}
- npm test
- npm build
- scp -o stricthostkeychecking=no -r ./nodes_project/* root@47.93.148.206:/root/
branches:
  only:
  - master
env:
  global: 
before_install:
- openssl aes-256-cbc -K $encrypted_756bcdda7b95_key -iv $encrypted_756bcdda7b95_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
   - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host 43.93.148.206\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
