language: node_js
node_js: stable

# S: Build Lifecycle
install:
  - npm install


#before_script:
 # - npm install -g gulp

#script:
#  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "xiaozhuxiaozhi"
  - git config user.email "2085188234@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${travis_token}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - devTest
env:
 global:
   - GH_REF: github.com/xiaozhuxiaozhi/nodes_project.git
